### ISSUE TITLE
Panic on long IRC messages

### ISSUE THREAD

**Issue by chrissexton** [velour/chat#54]
```
Message{
        ID: "1483455631.011986"
        From: User{
                ID: "U1S4MA61K"
                Nick: "seped"
                FullName: "Rob Uhl"
                DisplayName: "seped"
                PhotoURL: "https://secure.gravatar.com/avatar/5977f58c8a27c25b009eb9ad1aba3245.jpg?s=192&d=https%!A(MISSING)%!F(MISSING)%!F(MISSING)a.slack-edge.com%!F(MISSING)7fa9%!F(MISSING)img%!F(MISSING)avatars%!F(MISSING)ava_0021-192.png"
        }
        Text: "just a custom extension, they're ruby scripts."
}
panic: failed to send mesage to #velour on IRC (irc.freenode.net:6697): Message is too long (249 bytes truncated): PRIVMSG #velour :<seped> Speaking of causing others physical pain, keith was playing with advent of code over the holidays. He was making tested. readable, and idiomatic solutions. I wrote up a solution to the first days problem to see if I'd make him regret his decision to bring a new life into this world.  `input.split(', ').each_with_object({x:0,y:0,h:0}){|cmd, data| data[:h] = (data[:h]+(cmd[0] == 'L' ? -1 : 1))%4; axis = (data[:h] % 2) == 0 ? :y : :x; old = data[axis]; data[axis] += ((data[:h]/2.0).flo

goroutine 1 [running]:
panic(0x671820, 0xc4203bef70)
        /home/cws/go/src/runtime/panic.go:500 +0x1a1
main.main()
        /home/cws/src/github.com/velour/chat/bridge/main.go:142 +0xd82
exit status 2
```

**Comment by eaburns** [comment]
This is a dup of #14.
