### ISSUE TITLE
telegram: EOF error

### ISSUE THREAD

**Issue by chrissexton** [velour/chat#74]
```
2017/01/11 20:49:04 Telegram RPC getUpdates {Offset:284720583 Timeout:100} faile
d: 502 Bad Gateway
2017/01/11 20:49:04 Bridge closed with error: failed to receive from velour-test
 on Telegram: EOF
2017/01/11 20:49:04 Telegram RPC sendMessage map[chat_id:-1001096014407 text:Bri
dge closed with error: failed to receive from velour-test on Telegram: EOF
 parse_mode:Markdown] failed: 502 Bad Gateway
panic: 502 Bad Gateway

goroutine 1 [running]:
panic(0x677140, 0xc420440510)
        /home/cws/go/src/runtime/panic.go:500 +0x1a1
main.main.func2(0xc420424380, 0x813400, 0xc420010380)
        /home/cws/src/github.com/velour/chat/bridge/main.go:72 +0x7e
main.main()
        /home/cws/src/github.com/velour/chat/bridge/main.go:162 +0x1197
2017/01/11 20:49:07 Telegram RPC getMe <nil> failed: 502 Bad Gateway
panic: 502 Bad Gateway

goroutine 1 [running]:
panic(0x677140, 0xc42043e760)
        /home/cws/go/src/runtime/panic.go:500 +0x1a1
main.main()
        /home/cws/src/github.com/velour/chat/bridge/main.go:68 +0x157f
2017/01/11 20:49:09 Telegram RPC getMe <nil> failed: 502 Bad Gateway
panic: 502 Bad Gateway

goroutine 1 [running]:
panic(0x677140, 0xc42043cd30)
        /home/cws/go/src/runtime/panic.go:500 +0x1a1
main.main()
        /home/cws/src/github.com/velour/chat/bridge/main.go:68 +0x157f
```

**Comment by eaburns** [comment]
I Googled around a bit, and consensus seems to be that this indicates a Telegram-side error. The fact that it's a 500-level error would corroborate that. I think that we should tag 500 errors as re-tryable during getUpdate polling and retry some fixed number of times before actually giving up.
